/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sprint1;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author intel dual core
 */
public class ConsultarCuentas extends javax.swing.JFrame {

    /**
     * Creates new form ConsultarCuentas
     */
    public ConsultarCuentas() {
        initComponents();
        this.setTitle("Visualizar Cuentas");
        setLocationRelativeTo(null);
        
         try {
            DefaultTableModel modelo = new DefaultTableModel();
            table.setModel(modelo);

            PreparedStatement ps = null;
            ResultSet rs = null;
            Conexion conn = new Conexion();
            Connection con = conn.getConexion();

            String sql = "SELECT cod_empleado, nombre, tipo_documento, num_documento, "
                              + " nacionalidad, sexo, direccion, telefono, email, fec_nacimiento,"
                              + " est_civil, fec_ingreso, cargo FROM registrar_cuentas_empleados";
            ps = con.prepareStatement(sql);
            rs = ps.executeQuery();

            ResultSetMetaData rsMd = (ResultSetMetaData) rs.getMetaData();
            int cantidadColumnas = rsMd.getColumnCount();

            modelo.addColumn("Código");
            modelo.addColumn("Nombre");
            modelo.addColumn("Tipo Documento");
            modelo.addColumn("Nº Documento");
            modelo.addColumn("Nacionalidad");
            modelo.addColumn("Sexo");
            modelo.addColumn("Direccion");
            modelo.addColumn("Telefono");
            modelo.addColumn("Email");
            modelo.addColumn("Fecha Nacimiento");
            modelo.addColumn("Estado Civil");
            modelo.addColumn("Fecha Ingreso");
            modelo.addColumn("Cargo");
            
            int[] anchos = {50,100,100,100,100,70,100,100,100,80,80,80,100};
            for (int i = 0; i < table.getColumnCount(); i++) {
                table.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);
            }

            while (rs.next()) {
                Object[] filas = new Object[cantidadColumnas];
                for (int i = 0; i < cantidadColumnas; i++) {
                    filas[i] = rs.getObject(i + 1);
                }
                modelo.addRow(filas);
            }

        } catch (SQLException ex) {
            System.err.println(ex.toString());
        }
        
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCuentas = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        txtRegresar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCuentas.setBackground(new java.awt.Color(255, 51, 255));
        lblCuentas.setFont(new java.awt.Font("Lucida Calligraphy", 1, 36)); // NOI18N
        lblCuentas.setForeground(new java.awt.Color(153, 0, 153));
        lblCuentas.setText("Cuentas Empleados");
        getContentPane().add(lblCuentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 420, -1));

        table.setAutoCreateRowSorter(true);
        table.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        table.setFont(new java.awt.Font("Georgia", 1, 11)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Tipo Documento", "Nº Documento", "Nacionalidad", "Sexo", "Direccion", "Telefono", "Email", "Fecha Nacimiento", "Estado Civil", "Fecha Ingreso", "Cargo"
            }
        ));
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 1290, 350));

        txtRegresar.setBackground(new java.awt.Color(0, 204, 204));
        txtRegresar.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        txtRegresar.setForeground(new java.awt.Color(153, 0, 153));
        txtRegresar.setText("Regresar");
        txtRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(txtRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 437, 150, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/banco su mano amiga logo.png"))); // NOI18N
        jLabel2.setText("lblLogo");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 10, 200, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo cuentas.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1310, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegresarActionPerformed
        JUsuarios vista = new JUsuarios();
        vista.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_txtRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultarCuentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultarCuentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultarCuentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultarCuentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultarCuentas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCuentas;
    private javax.swing.JTable table;
    private javax.swing.JButton txtRegresar;
    // End of variables declaration//GEN-END:variables
}
